name: Biome
on:
  push:
    branches:
      - master

jobs:
  Lint:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Biome
        run: bun check
