name: Tests
on:
  push:
    branches:
      - master

jobs:
  Lint:
    name: Tests
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: "long_string"
      PORT: "3000"
      ENV: "test"
    steps:
      - uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Tests
        run: bun test
